version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_CATCOIN_NODE_IP
      APP_PORT: 3000

  app:
    image: ahmedbodi/umbrel-catcoin:v2.2.2
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 15m30s
    # these ports are exposed for external connections to catcoind
    ports:
      - "${APP_CATCOIN_P2P_PORT}:${APP_CATCOIN_P2P_PORT}"
      - "${APP_CATCOIN_RPC_PORT}:${APP_CATCOIN_RPC_PORT}"
    volumes:
      - ${APP_DATA_DIR}/data:/data # data/app and data/catcoin
    environment:
      # DATA DIRECTORY SETTINGS
      # CATCOIN_DIR: catcoin-dir-override
      # APP_STATE_DIR: app-state-dir-override

      # CATCOIND BINARY SETTINGS
      # CATCOIND_BIN: catcoind-binary-path-override
      # comma-delimited list of extra startup flags to pass to catcoind
      CATCOIND_EXTRA_ARGS: "-deprecatedrpc=create_bdb" # We can remove depratedrpc=create_bdb in a future update once Jam (JoinMarket) implements descriptor wallet support

      # CATCOIND CONF FILE SETTINGS
      APPS_SUBNET: "${NETWORK_IP}/16" # used for rpcallowip
      P2P_PORT: "${APP_CATCOIN_P2P_PORT}" # port, bind (also used for connect details)
      P2P_WHITEBIND_PORT: "${APP_CATCOIN_P2P_WHITEBIND_PORT}" # Additional inbound P2P listener granting whitelisted permissions (whitebind) to this port; for trusted internal apps only; do not publish externally
      RPC_PORT: "${APP_CATCOIN_RPC_PORT}" # rpcport (also used for rpc client and connect details)
      TOR_PORT: "${APP_CATCOIN_TOR_PORT}" # bind=onion
      ZMQ_RAWBLOCK_PORT: "${APP_CATCOIN_ZMQ_RAWBLOCK_PORT}" # zmqpubrawblock
      ZMQ_RAWTX_PORT: "${APP_CATCOIN_ZMQ_RAWTX_PORT}" # zmqpubrawtx
      ZMQ_HASHBLOCK_PORT: "${APP_CATCOIN_ZMQ_HASHBLOCK_PORT}" # zmqpubhashblock
      ZMQ_SEQUENCE_PORT: "${APP_CATCOIN_ZMQ_SEQUENCE_PORT}" # zmqpubsequence
      ZMQ_HASHTX_PORT: "${APP_CATCOIN_ZMQ_HASHTX_PORT}" # zmqpubhashtx
      TOR_HOST: "${APP_CATCOIN_TOR_PROXY_IP}" # proxy, onion, torcontrol
      TOR_SOCKS_PORT: "9050" # proxy, onion
      TOR_CONTROL_PORT: "9051" # torcontrol
      TOR_CONTROL_PASSWORD: "moneyprintergobrrr" # torpassword
      I2P_HOST: "${APP_CATCOIN_I2P_DAEMON_IP}" # i2psam
      I2P_SAM_PORT: "7656" # i2psam

      # RPC CLIENT SETTINGS
      CATCOIND_IP: "${APP_CATCOIN_NODE_IP}" # host for the rpc client. Also used for catcoind conf file rpcbind & bind.
      RPC_USER: "${APP_CATCOIN_RPC_USER}" # also shown in the connect modal
      RPC_PASS: "${APP_CATCOIN_RPC_PASS}" # also shown in the connect modal

      # CONNECTION DETAILS (shown to user in the connect modal)
      DEVICE_DOMAIN_NAME: "${DEVICE_DOMAIN_NAME}"
      P2P_HIDDEN_SERVICE: "${APP_CATCOIN_P2P_HIDDEN_SERVICE}"
      RPC_HIDDEN_SERVICE: "${APP_CATCOIN_RPC_HIDDEN_SERVICE}"
    networks:
      default:
        ipv4_address: $APP_CATCOIN_NODE_IP

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
    networks:
      default:
        ipv4_address: "${APP_CATCOIN_TOR_PROXY_IP}"

  i2pd_daemon:
    image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    user: "root"
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --loglevel=error
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/i2pd:/home/i2pd/data
    networks:
      default:
        ipv4_address: "${APP_CATCOIN_I2P_DAEMON_IP}"
